// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Product.InventoryManagement.Persistence.DatabaseContext;

#nullable disable

namespace Product.InventoryManagement.Persistence.Migrations
{
    [DbContext(typeof(InventoryDatabaseContext))]
    [Migration("20251002064538_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Product.InventoryManagement.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6c93b54b-0ae3-4294-9ae6-4c5280ee5c63"),
                            CreatedAt = new DateTime(2025, 10, 2, 14, 45, 37, 2, DateTimeKind.Local).AddTicks(5165),
                            Description = "Mouse na malibag",
                            Name = "Mouse",
                            Price = 1400.99m,
                            Quantity = 12,
                            UpdatedAt = new DateTime(2025, 10, 2, 14, 45, 37, 3, DateTimeKind.Local).AddTicks(7298)
                        },
                        new
                        {
                            Id = new Guid("5ea76040-f484-4ae0-8486-e690d8a8c88e"),
                            CreatedAt = new DateTime(2025, 10, 2, 14, 45, 37, 3, DateTimeKind.Local).AddTicks(7694),
                            Description = "Keyboard na sira Enter key",
                            Name = "Keyboard",
                            Price = 2250m,
                            Quantity = 6,
                            UpdatedAt = new DateTime(2025, 10, 2, 14, 45, 37, 3, DateTimeKind.Local).AddTicks(7697)
                        },
                        new
                        {
                            Id = new Guid("9c815d01-cc82-4adb-957b-850a6a7a2f2b"),
                            CreatedAt = new DateTime(2025, 10, 2, 14, 45, 37, 3, DateTimeKind.Local).AddTicks(7700),
                            Description = "Pwedeng pang halo sa sinigang",
                            Name = "Headphones",
                            Price = 1600.50m,
                            Quantity = 24,
                            UpdatedAt = new DateTime(2025, 10, 2, 14, 45, 37, 3, DateTimeKind.Local).AddTicks(7701)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
