// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Product.InventoryManagement.Persistence.DatabaseContext;

#nullable disable

namespace Product.InventoryManagement.Persistence.Migrations
{
    [DbContext(typeof(InventoryDatabaseContext))]
    [Migration("20251003072736_added-project-requirements-constraints")]
    partial class addedprojectrequirementsconstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Product.InventoryManagement.Domain.Entities.InventoryTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UnitsAdded")
                        .HasColumnType("int");

                    b.Property<int>("UnitsRemoved")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Product.InventoryManagement.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2025, 10, 3, 15, 27, 35, 496, DateTimeKind.Local).AddTicks(416));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2025, 10, 3, 15, 27, 35, 499, DateTimeKind.Local).AddTicks(3641));

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b532fb9b-cd64-43d8-84be-2245d996c5e6"),
                            CreatedAt = new DateTime(2025, 10, 3, 15, 27, 35, 499, DateTimeKind.Local).AddTicks(6391),
                            Description = "Mouse na malibag",
                            Name = "Mouse",
                            Price = 1400.99m,
                            Quantity = 12,
                            UpdatedAt = new DateTime(2025, 10, 3, 15, 27, 35, 499, DateTimeKind.Local).AddTicks(6656)
                        },
                        new
                        {
                            Id = new Guid("6df4a032-cfb9-4777-8173-e440da1330e9"),
                            CreatedAt = new DateTime(2025, 10, 3, 15, 27, 35, 499, DateTimeKind.Local).AddTicks(6910),
                            Description = "Keyboard na sira Enter key",
                            Name = "Keyboard",
                            Price = 2250m,
                            Quantity = 6,
                            UpdatedAt = new DateTime(2025, 10, 3, 15, 27, 35, 499, DateTimeKind.Local).AddTicks(6912)
                        },
                        new
                        {
                            Id = new Guid("32b28a0d-403b-4c39-a25b-9f1f67a3fe7a"),
                            CreatedAt = new DateTime(2025, 10, 3, 15, 27, 35, 499, DateTimeKind.Local).AddTicks(6915),
                            Description = "Pwedeng pang halo sa sinigang",
                            Name = "Headphones",
                            Price = 1600.50m,
                            Quantity = 24,
                            UpdatedAt = new DateTime(2025, 10, 3, 15, 27, 35, 499, DateTimeKind.Local).AddTicks(6916)
                        });
                });

            modelBuilder.Entity("Product.InventoryManagement.Domain.Entities.InventoryTransaction", b =>
                {
                    b.HasOne("Product.InventoryManagement.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
