// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Product.InventoryManagement.Persistence.DatabaseContext;

#nullable disable

namespace Product.InventoryManagement.Persistence.Migrations
{
    [DbContext(typeof(InventoryDatabaseContext))]
    [Migration("20251008030450_delete-using-sp")]
    partial class deleteusingsp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Product.InventoryManagement.Domain.Entities.InventoryTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UnitsAdded")
                        .HasColumnType("int");

                    b.Property<int>("UnitsRemoved")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Product.InventoryManagement.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b6aab9b5-7dcb-4507-b09e-51ea4de3502c"),
                            CreatedAt = new DateTime(2025, 10, 8, 11, 4, 49, 488, DateTimeKind.Local).AddTicks(6622),
                            Description = "Mouse na malibag",
                            Name = "Mouse",
                            Price = 1400.99m,
                            Quantity = 12,
                            UpdatedAt = new DateTime(2025, 10, 8, 11, 4, 49, 489, DateTimeKind.Local).AddTicks(8651)
                        },
                        new
                        {
                            Id = new Guid("3b1e19fe-7a54-44c3-95e2-bc8ee9e977d9"),
                            CreatedAt = new DateTime(2025, 10, 8, 11, 4, 49, 489, DateTimeKind.Local).AddTicks(9034),
                            Description = "Keyboard na sira Enter key",
                            Name = "Keyboard",
                            Price = 2250m,
                            Quantity = 6,
                            UpdatedAt = new DateTime(2025, 10, 8, 11, 4, 49, 489, DateTimeKind.Local).AddTicks(9036)
                        },
                        new
                        {
                            Id = new Guid("3416aa1d-0080-405d-8307-d49c81575a52"),
                            CreatedAt = new DateTime(2025, 10, 8, 11, 4, 49, 489, DateTimeKind.Local).AddTicks(9041),
                            Description = "Pwedeng pang halo sa sinigang",
                            Name = "Headphones",
                            Price = 1600.50m,
                            Quantity = 24,
                            UpdatedAt = new DateTime(2025, 10, 8, 11, 4, 49, 489, DateTimeKind.Local).AddTicks(9041)
                        });
                });

            modelBuilder.Entity("Product.InventoryManagement.Domain.Entities.InventoryTransaction", b =>
                {
                    b.HasOne("Product.InventoryManagement.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
