// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Product.InventoryManagement.Persistence.DatabaseContext;

#nullable disable

namespace Product.InventoryManagement.Persistence.Migrations
{
    [DbContext(typeof(InventoryDatabaseContext))]
    [Migration("20251002065421_add-price-value-contraints")]
    partial class addpricevaluecontraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Product.InventoryManagement.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f3bd4ce2-2731-46b4-91ad-460d14ba6ea1"),
                            CreatedAt = new DateTime(2025, 10, 2, 14, 54, 20, 424, DateTimeKind.Local).AddTicks(2331),
                            Description = "Mouse na malibag",
                            Name = "Mouse",
                            Price = 1400.99m,
                            Quantity = 12,
                            UpdatedAt = new DateTime(2025, 10, 2, 14, 54, 20, 425, DateTimeKind.Local).AddTicks(3822)
                        },
                        new
                        {
                            Id = new Guid("5ade0064-50ab-404f-8e95-6a0b9a44bcab"),
                            CreatedAt = new DateTime(2025, 10, 2, 14, 54, 20, 425, DateTimeKind.Local).AddTicks(4207),
                            Description = "Keyboard na sira Enter key",
                            Name = "Keyboard",
                            Price = 2250m,
                            Quantity = 6,
                            UpdatedAt = new DateTime(2025, 10, 2, 14, 54, 20, 425, DateTimeKind.Local).AddTicks(4210)
                        },
                        new
                        {
                            Id = new Guid("c0b5afb1-c316-40db-96d6-55d2f3cf641d"),
                            CreatedAt = new DateTime(2025, 10, 2, 14, 54, 20, 425, DateTimeKind.Local).AddTicks(4223),
                            Description = "Pwedeng pang halo sa sinigang",
                            Name = "Headphones",
                            Price = 1600.50m,
                            Quantity = 24,
                            UpdatedAt = new DateTime(2025, 10, 2, 14, 54, 20, 425, DateTimeKind.Local).AddTicks(4223)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
